server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${local-db.mysql.host}:${local-db.mysql.port}/${local-db.mysql.name}
    username: root
    password: ${local-db.mysql.password}
    hikari:
      maximum-pool-size: 50 # 동시성 테스트를 위한 커넥션 풀 크기 증가 (기본값: 10)
      minimum-idle: 10
      connection-timeout: 10000  # 10초
      validation-timeout: 5000
      idle-timeout: 600000  # 10분
      max-lifetime: 1800000  # 30분

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl.auto: create
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false

  config:
    import:
      - security/application-local.yml

logging:
  level:
    org:
      hibernate:
        type: info
